def build(bld):


    # the following sdk component is used for configuration purposes in several components
    # in order to keep the components generic and commonly usable in all applications
    bld.sdkcomponent(
        name            = "cifXApplicationConfig_sdk",
        export_defines  = [
#                           "DONT_USE_CHANNEL0",       # Communication channel 0 is implicitly used by default, it must be explicitly disabled
                           "USE_CHANNEL0",             # Communication channel 0 is anyway implicitly opened, this define just for readability
                           "USE_CHANNEL1",            # Communication channel 1 is opened - e.g. SocketIf or WebIf 
#                           "USE_CHANNEL2",            # Communication channel 2 is opened - e.g. netPROXY channel 
                            "CONSOLE_MODE",            # printf debug outputs 
#                            "DONT_USE_COMMAND_LOOKUP", # Do not use the packet command look up table, which is specific to the used protocol stack
#                           "ONLY_MAILBOX",            # no cyclic IO data handler registered, very special case e.g. for OpenModbusTCP message mode
                           ],
    )
    
    bld.sdkcomponent(
        name            = "cmsis_configuration_sdk",
        export_defines  = [
                           "__STACK_SIZE = 0x00002000",
                           "__HEAP_SIZE =  0x00008000",
                           ],
        )

