def build(bld):
    
    toolchain = bld.env["UsedToolchain"]
    if not toolchain:
        bld.fatal('Environment parameter "UsedToolchain" is not available! Make sure to provide the environment parameter "UsedToolchain" in the root wscript file of your project. e.g.: conf.env["UsedToolchain"] = "gccarmemb"')
    
    platform  = bld.env["UsedPlatform"]
    if not platform:
        bld.fatal('Environment parameter "UsedPlatform" is not available! Make sure to provide the environment parameter "UsedPlatform" in the root wscript file of your project. e.g.: conf.env["UsedPlatform"]  = "netx90"')
      
    comp_prefix = bld.get_name_prefix(
        toolchain = toolchain,
        platform  = platform)
    
# Component cifXApplication ------------------------------------------------------------    
    netx_studio_sources = [
        "Sources/App_Application.c", 
        "Sources/App_ApplicationFunctions.c", 
        "Sources/App_EventHandler.c", 
        "Sources/App_SystemPackets.c",
        "Sources/App_TerminalHandler.c", 
        "Sources/App_PacketCommunication.c",
        "Sources/App_SockIfFunctions.c",
        "Sources/App_FileSystemPackets.c",
        ]

    includes = [
        "Includes",
        ]
        
    bld.stlib( 
        target          = "cifXApplication",
        name            = comp_prefix + "cifXApplication",
        description     = "cifX Application - protocol independent body",
        displaygroup    = "Libraries",
        platform        = platform,
        toolchain       = toolchain, 
        use             = [                           
                           "cifXApplicationConfig_sdk",
                           "cifXToolkit_sdk",
                           "CMSIS_sdk",
                           "cmsis_configuration_sdk",
                           "Hil_Definition_cifXApi_sdk",                           
                           "Hil_Definition_netXFirmware_sdk",
                           "hostabstractionlayer_sdk",                           
                           "netx_drv_sdk",
                           "netx_drv_configuration_sdk",
                           "SocketDefinitions_sdk",                           
                          ],
        source          = ["Sources/App_EventHandler.c"] + ["Sources/App_SystemPackets.c"] + ["Sources/App_TerminalHandler.c"] + ["Sources/App_PacketCommunication.c"] + ["Sources/App_Application.c"] + ["Sources/App_ApplicationFunctions.c"] + ["Sources/App_SockIfFunctions.c"] + ["Sources/App_FileSystemPackets.c"],
        includes        = includes,
        export_includes = includes,
        )
    
    bld.sdkcomponent(
        name            = "cifXApplication_sdk",
        export_includes = includes,
        )
    